### PR TITLE
[WIP] Version 6

### PR DESCRIPTION
**Pull request by grikomsn**

### CODE REVIEW

**Comment by grikomsn** [comment]
#### 📝Changed routes:


| [**/events**](https://surabayajsorg-git-v6.surabayajs.vercel.app/events) | [**/**](https://surabayajsorg-git-v6.surabayajs.vercel.app/) |
|:-:|:-:|
|<a href="https://surabayajsorg-git-v6.surabayajs.vercel.app/events">Screenshot of /events</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/E3GPlatZVXvgNvkDAcFlL4IzSdA_.png">(view full size)</a> |<a href="https://surabayajsorg-git-v6.surabayajs.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/J042p1BsSMQfsNGENcvnr9P_Mqw_.png">(view full size)</a> |





7 deleted routes:
- **/404**
- **/_error**
- **/api/events**
- **/api/socials**
- **/coc**
- **/contact**
- **/events/[slug]**

Commit d7708a04e414b3cdd50e9399574bfdf7470cef4d (https://surabayajsorg-git-v6.surabayajs.vercel.app).

**Comment by joshuanatanielnm** [comment]
love the wave, and card transition 👍

**Review by joshuanatanielnm — APPROVED** [review]
nice

**Review by baralogi — COMMENTED** [review]
nice enhancement! good job

**Pull request merged**
